export const productActionTypes = {
    ADD_ITEM_FOR_BOOKING: 'SET_ITEM_FOR_BOOKING',
    CONFIRM_ITEM_FOR_BOOKING: 'CONFIRM_ITEM_FOR_BOOKING',
    REMOVE_ITEM_FROM_BOOKING: 'REMOVE_ITEM_FROM_BOOKING'
}